Repository SOPT-all/36-COLLABORATION-ANDROID-ALAMI, pull requests merged in 2025-05, with the labels that each got.

#11 [FEAT/#10] 공통 컴포넌트 버튼 구현
  app/src/main/java/org/sopt/alami/core/designsystem/component/AlamiButton.kt
Labels: FEAT✨, 🚀민재🚀

#13 [FEAT/#9] 알람끄기, 아침 화면 UI 만들었어요
  app/src/main/AndroidManifest.xml
  app/src/main/java/org/sopt/alami/core/designsystem/theme/Type.kt
  app/src/main/java/org/sopt/alami/core/util/ModfierExt.kt
  app/src/main/java/org/sopt/alami/presentation/alarmdismiss/AlarmDismissScreen.kt
  app/src/main/java/org/sopt/alami/presentation/morning/MorningScreen.kt
  app/src/main/java/org/sopt/alami/presentation/morning/component/MorningSurface.kt
  app/src/main/java/org/sopt/alami/presentation/morning/component/TodaySentence.kt
  app/src/main/java/org/sopt/alami/presentation/morning/component/TodayWeatherInfo.kt
  app/src/main/java/org/sopt/alami/presentation/morning/model/WeatherIconState.kt
  app/src/main/res/drawable/dismiss_alarm_background.png
  app/src/main/res/drawable/ic_location_12.xml
  app/src/main/res/drawable/ic_morning_arrow_right_16.xml
  app/src/main/res/drawable/ic_morning_cloud_32.xml
  app/src/main/res/drawable/ic_morning_mood_24.png
  app/src/main/res/drawable/ic_morning_rain_32.xml
  app/src/main/res/drawable/ic_morning_sun_32.xml
  app/src/main/res/drawable/morning_background.png
Labels: FEAT✨, 🚀민재🚀

#15 [Feat/#12] BottomNavigationBar 구현
  app/src/main/AndroidManifest.xml
  app/src/main/java/org/sopt/alami/presentation/MainActivity.kt
  app/src/main/java/org/sopt/alami/presentation/alarm/AlarmScreen.kt
  app/src/main/java/org/sopt/alami/presentation/alarm/navigation/AlarmNavigation.kt
  app/src/main/java/org/sopt/alami/presentation/main/MainActivity.kt
  app/src/main/java/org/sopt/alami/presentation/main/MainNavHost.kt
  app/src/main/java/org/sopt/alami/presentation/main/MainNavigator.kt
  app/src/main/java/org/sopt/alami/presentation/main/MainScreen.kt
  app/src/main/java/org/sopt/alami/presentation/main/MainTabType.kt
  app/src/main/java/org/sopt/alami/presentation/main/component/MainBottomBar.kt
  app/src/main/java/org/sopt/alami/presentation/morning/navigation/MorningNavigation.kt
  app/src/main/java/org/sopt/alami/presentation/report/ReportScreen.kt
  app/src/main/java/org/sopt/alami/presentation/report/navigation/ReportNavigation.kt
  app/src/main/java/org/sopt/alami/presentation/setting/SettingScreen.kt
  app/src/main/java/org/sopt/alami/presentation/setting/navigation/SettingNavigation.kt
  app/src/main/java/org/sopt/alami/presentation/sleep/SleepScreen.kt
  app/src/main/java/org/sopt/alami/presentation/sleep/navigation/SleepNavigation.kt
  app/src/main/res/drawable/ic_clockoff_28.xml
  app/src/main/res/drawable/ic_clockon_28.xml
  app/src/main/res/drawable/ic_morningoff_28.xml
  app/src/main/res/drawable/ic_morningon_28.xml
  app/src/main/res/drawable/ic_report_28.xml
  app/src/main/res/drawable/ic_setting_28.xml
  app/src/main/res/drawable/ic_sleep_28.xml
  app/src/main/res/values/strings.xml
Labels: FEAT✨, 🚀아연🚀

#18 [Feat/#16] Alarm UI 구현
  app/src/main/java/org/sopt/alami/presentation/MainActivity.kt
  app/src/main/java/org/sopt/alami/presentation/alarm/AlarmScreen.kt
  app/src/main/java/org/sopt/alami/presentation/alarm/component/AddAlarmButton.kt
  app/src/main/java/org/sopt/alami/presentation/alarm/component/AlarmCard.kt
  app/src/main/java/org/sopt/alami/presentation/alarm/component/AlarmSurface.kt
  app/src/main/java/org/sopt/alami/presentation/alarm/model/AlarmCardState.kt
  app/src/main/java/org/sopt/alami/presentation/alarm/model/AlarmTime.kt
  app/src/main/java/org/sopt/alami/presentation/alarm/model/DayType.kt
  app/src/main/java/org/sopt/alami/presentation/alarm/model/MeridiemType.kt
  app/src/main/java/org/sopt/alami/presentation/alarm/viewmodel/AlarmViewModel.kt
  app/src/main/java/org/sopt/alami/presentation/main/MainNavigator.kt
  app/src/main/java/org/sopt/alami/presentation/report/ReportScreen.kt
  app/src/main/java/org/sopt/alami/presentation/setting/SettingScreen.kt
  app/src/main/java/org/sopt/alami/presentation/sleep/SleepScreen.kt
  app/src/main/res/drawable/ic_alarm_menu_16.xml
  app/src/main/res/drawable/ic_alarm_mission_16.xml
  app/src/main/res/drawable/ic_floating_calendar_28.xml
  app/src/main/res/drawable/ic_floating_clock_28.xml
  app/src/main/res/drawable/ic_floating_close_28.xml
  app/src/main/res/drawable/ic_floating_plus_28.xml
  app/src/main/res/drawable/ic_floating_quick_28.xml
  app/src/main/res/drawable/ic_header_menu_32.xml
  app/src/main/res/drawable/img_home_zzz_45.png
Labels: FEAT✨, 🚀아연🚀

#17 Feat/#14 alarm setting UI 구현했습니다
  app/src/main/java/org/sopt/alami/presentation/setting/SettingScreen.kt
  app/src/main/java/org/sopt/alami/presentation/setting/component/AddMission.kt
  app/src/main/java/org/sopt/alami/presentation/setting/component/AlarmPicker.kt
  app/src/main/java/org/sopt/alami/presentation/setting/component/DateSelect.kt
  app/src/main/java/org/sopt/alami/presentation/setting/component/ScreenDivider.kt
  app/src/main/java/org/sopt/alami/presentation/setting/component/SettingBox.kt
  app/src/main/java/org/sopt/alami/presentation/setting/component/SoundProgess.kt
  app/src/main/java/org/sopt/alami/presentation/setting/model/AlarmSettingViewModel.kt
  app/src/main/java/org/sopt/alami/presentation/setting/model/SettingItem.kt
  app/src/main/res/drawable/ic_add_mission.xml
  app/src/main/res/drawable/ic_add_mission_png.jpg
  app/src/main/res/drawable/ic_back.xml
  app/src/main/res/drawable/ic_button_detail.xml
  app/src/main/res/drawable/ic_date_checkbox.xml
  app/src/main/res/drawable/ic_date_friday.xml
  app/src/main/res/drawable/ic_date_monday.xml
  app/src/main/res/drawable/ic_date_saturday.xml
  app/src/main/res/drawable/ic_date_sunday.xml
  app/src/main/res/drawable/ic_date_thursday.xml
  app/src/main/res/drawable/ic_date_tuesday.xml
  app/src/main/res/drawable/ic_date_wendseday.xml
  app/src/main/res/drawable/ic_mission_off.xml
  app/src/main/res/drawable/ic_mission_on.xml
  app/src/main/res/drawable/ic_mute_off.xml
  app/src/main/res/drawable/ic_mute_on.xml
  app/src/main/res/drawable/ic_vibe.xml
  app/src/main/res/drawable/img_setting_mission.png
Labels: FEAT✨, 🚀주완🚀

#23 [Feat/#21] 알람 목록 api 연결
  app/src/main/AndroidManifest.xml
  app/src/main/java/org/sopt/alami/data/di/ServiceModule.kt
  app/src/main/java/org/sopt/alami/data/dto/AlarmListDto.kt
  app/src/main/java/org/sopt/alami/data/dto/AlarmTimeCheckDto.kt
  app/src/main/java/org/sopt/alami/data/repository/AlarmListRepository.kt
  app/src/main/java/org/sopt/alami/data/service/AlarmListService.kt
  app/src/main/java/org/sopt/alami/presentation/alarm/AlarmScreen.kt
  app/src/main/java/org/sopt/alami/presentation/alarm/model/AlarmCardState.kt
  app/src/main/java/org/sopt/alami/presentation/alarm/navigation/AlarmNavigation.kt
  app/src/main/java/org/sopt/alami/presentation/alarm/viewmodel/AlarmViewModel.kt
  app/src/main/java/org/sopt/alami/presentation/alarmdismiss/navigation/AlarmDismissNavigation.kt
  app/src/main/java/org/sopt/alami/presentation/main/MainNavHost.kt
  app/src/main/java/org/sopt/alami/presentation/main/MainNavigator.kt
  app/src/main/java/org/sopt/alami/presentation/setting/SettingScreen.kt
Labels: FEAT✨, 🚀아연🚀

#22 [Feat/#19] 오늘의 문장과 날씨 API를 연결해요
  app/build.gradle.kts
  app/src/main/AndroidManifest.xml
  app/src/main/java/org/sopt/alami/core/network/AuthInterceptor.kt
  app/src/main/java/org/sopt/alami/core/network/BaseResponse.kt
  app/src/main/java/org/sopt/alami/data/di/ServiceModule.kt
  app/src/main/java/org/sopt/alami/data/dto/DummyDto.kt
  app/src/main/java/org/sopt/alami/data/dto/response/TodaySentenceResponseDto.kt
  app/src/main/java/org/sopt/alami/data/dto/response/TodayWeatherResponseDto.kt
  app/src/main/java/org/sopt/alami/data/mapper/MorningMapper.kt
  app/src/main/java/org/sopt/alami/data/repository/AlarmListRepository.kt
  app/src/main/java/org/sopt/alami/data/repository/DummyRepository.kt
  app/src/main/java/org/sopt/alami/data/repository/MorningRepository.kt
  app/src/main/java/org/sopt/alami/data/service/MorningService.kt
  app/src/main/java/org/sopt/alami/presentation/morning/MorningScreen.kt
  app/src/main/java/org/sopt/alami/presentation/morning/MorningViewModel.kt
  app/src/main/java/org/sopt/alami/presentation/morning/component/TodaySentence.kt
  app/src/main/java/org/sopt/alami/presentation/morning/model/MorningSentence.kt
  app/src/main/java/org/sopt/alami/presentation/morning/model/MorningWeather.kt
  app/src/main/java/org/sopt/alami/presentation/morning/model/WeatherIconState.kt
  app/src/main/java/org/sopt/alami/presentation/morning/model/WeatherType.kt
  app/src/main/java/org/sopt/alami/presentation/setting/SettingScreen.kt
  app/src/main/java/org/sopt/alami/presentation/setting/component/AddMission.kt
  app/src/main/java/org/sopt/alami/presentation/setting/component/AlarmPicker.kt
  app/src/main/java/org/sopt/alami/presentation/setting/component/DateSelect.kt
  app/src/main/java/org/sopt/alami/presentation/setting/component/ScreenDivider.kt
  app/src/main/java/org/sopt/alami/presentation/setting/component/SettingBox.kt
  app/src/main/java/org/sopt/alami/presentation/setting/component/SoundProgess.kt
  app/src/main/java/org/sopt/alami/presentation/setting/model/AlarmSettingViewModel.kt
  app/src/main/java/org/sopt/alami/presentation/setting/model/SettingItem.kt
  app/src/main/res/drawable/img_today_quote1_and.png
  app/src/main/res/drawable/img_today_quote2_and.png
  app/src/main/res/drawable/img_today_quote3_and.png
  app/src/main/res/drawable/img_today_quote4_and.png
  app/src/main/res/drawable/img_today_quote5_and.png
  app/src/main/res/drawable/img_today_quote6_and.png
Labels: FEAT✨, 🚀민재🚀

#24 [Feat/#20] 알람 추가 api 연결
  app/src/main/java/org/sopt/alami/core/network/RetrofitModule.kt
  app/src/main/java/org/sopt/alami/data/di/RepositoryModule.kt
  app/src/main/java/org/sopt/alami/data/di/ServiceModule.kt
  app/src/main/java/org/sopt/alami/data/dto/request/AddAlarmRequest.kt
  app/src/main/java/org/sopt/alami/data/dto/response/AddAlarmResponse.kt
  app/src/main/java/org/sopt/alami/data/repository/AlarmRepository.kt
  app/src/main/java/org/sopt/alami/data/service/AddAlarmService.kt
  app/src/main/java/org/sopt/alami/presentation/alarm/AlarmScreen.kt
  app/src/main/java/org/sopt/alami/presentation/alarm/component/AddAlarmButton.kt
  app/src/main/java/org/sopt/alami/presentation/main/MainNavHost.kt
  app/src/main/java/org/sopt/alami/presentation/setting/SettingScreen.kt
  app/src/main/java/org/sopt/alami/presentation/setting/component/AlarmPicker.kt
  app/src/main/java/org/sopt/alami/presentation/setting/component/FloatingAlamiButton.kt
  app/src/main/java/org/sopt/alami/presentation/setting/model/AlarmSettingViewModel.kt
  app/src/main/java/org/sopt/alami/presentation/setting/navigation/SettingNavigation.kt
  app/src/main/res/xml/network_security_config.xml
Labels: FEAT✨, 🚀주완🚀
